### ISSUE TITLE
Build fails on make command on Linux59 kernel

### ISSUE THREAD

**Issue by HitCoder9768** [Netgear-A6210-linux-driver/Netgear-A6210#18]
I've been using this driver for as long as I can remember. With Linux59 I am getting the following error:

```
/home/hitcoder/Netgear-A6210-master/os/linux/../../os/linux/cfg80211/cfg80211.c: At top level:
/home/hitcoder/Netgear-A6210-master/os/linux/../../os/linux/cfg80211/cfg80211.c:2505:3: error: ‘struct cfg80211_ops’ has no member named ‘mgmt_frame_register’
 2505 |  .mgmt_frame_register = CFG80211_OpsMgmtFrameRegister,
      |   ^~~~~~~~~~~~~~~~~~~
/home/hitcoder/Netgear-A6210-master/os/linux/../../os/linux/cfg80211/cfg80211.c:2505:25: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, s32,  s32)’ {aka ‘int (*)(struct wiphy *, struct net_device *, int,  int)’} from incompatible pointer type ‘void (*)(struct wiphy *, struct wireless_dev *, u16,  bool)’ {aka ‘void (*)(struct wiphy *, struct wireless_dev *, short unsigned int,  _Bool)’} [-Werror=incompatible-pointer-types]
 2505 |  .mgmt_frame_register = CFG80211_OpsMgmtFrameRegister,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hitcoder/Netgear-A6210-master/os/linux/../../os/linux/cfg80211/cfg80211.c:2505:25: note: (near initialization for ‘CFG80211_Ops.set_cqm_rssi_range_config’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:283: /home/hitcoder/Netgear-A6210-master/os/linux/../../os/linux/cfg80211/cfg80211.o] Error 1
make[1]: *** [Makefile:1787: /home/hitcoder/Netgear-A6210-master/os/linux] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.9.16-1-MANJARO/build'
make: *** [Makefile:65: debug] Error 2

```

If any more info is required I will do my best to provide.

**Comment by genodeftest** [comment]
The code will probably need some adaptations to be compiled against the 5.9 kernel. If you can, please feel free to fix the code and create a pull request.

**Comment by HitCoder9768** [comment]
I did have a dig through the source to attempt to fix the issue but I'm not as experienced in C as I would like to be so I guess this will have to be on hold for now unless somebody else is available to make the changes

I don't really know what the compile errors shown mean, if i did I'd do more diagnostics

**Comment by HitCoder9768** [comment]
Never mind, was able to fix the problem. I modified the line above 2505

`#if (LINUX_VERSION_CODE >= KERNEL_VERSION(2,6,37) && LINUX_VERSION_CODE < KERNEL_VERSION(5,9,0))`

I hope this doesn't end up being an extremely hacky fix, but regardless I made a pull request and it's working fine on my end.
