### ISSUE TITLE
Has this been merged into the Linux kernel?

### ISSUE THREAD

**Issue by lil5** [Netgear-A6210-linux-driver/Netgear-A6210#28]
From this comment I found on Amazon it seems like at least fedora has the correct drivers. 

https://www.amazon.nl/Netgear-Ac1200-Wi-Fi-Adapter-A6210-100Pas/dp/B00MRVJY1G

![image](https://user-images.githubusercontent.com/17646836/130270635-2c5d3d9f-73c9-4a43-a8b2-fb99c44fd424.png)

I would like to know if there is any knowledge of this.

**Comment by poscat0x04** [comment]
Indeed, the name of the kernel module is mt76x2e.

**Comment by genodeftest** [comment]
Thank you for this info! I've added a deprecation notice to the Readme.md.
