### ISSUE TITLE
Incompatible with linux >= 5.4

### ISSUE THREAD

**Issue by Nagefire** [Netgear-A6210-linux-driver/Netgear-A6210#5]
As far as I know, my branch has been the most updated because I use a rolling release distro, so my driver breaks first. My code is already merged, so we should have compatibility up to version 5.4. However, the latest error has been giving me trouble, the log can be found [here](https://gitlab.com/snippets/1934763). Attempting to track down this issue led me to a macro declaration in the linux kernel source code. However, this macro is defined in at least 3 separate headers and undefined then defined again in several cases, so I haven't been able to find the actual cause of the error yet.

**Comment by genodeftest** [comment]
Try using Eclipse IDE with CDT installed. Does the macro expansion work there? I can't get it to work here but I'm probably missing some compile flags…

**Comment by genodeftest** [comment]
I just added the compile flags (extracted them from running `make` with `--trace` and manually copied them to the .cproject file) and now eclipse is horribly slow ([my .cproject file](https://gist.github.com/genodeftest/f9f8678fd406aee79a5d81e78b3638f4)), can expand macros but fails to expand this one.

**Comment by genodeftest** [comment]
I *think* I have a fix in #7. With that, it compiles on 5.4 for me. Would you please review it?

**Comment by Nagefire** [comment]
Fixed by #7
